name = "autoreactt_bot"
main = "api/worker.js"
compatibility_date = "2024-06-02"

[vars]
BOT_TOKEN = "7702285784:AAEsYXobX7d3E2eFu89Hj7KjX99kfpG0Rcg"
BOT_USERNAME = "autoreactt_bot"
EMOJI_LIST = "ğŸ‘â¤ğŸ”¥ğŸ¥°ğŸ‘ğŸ˜ğŸ‰ğŸ¤©ğŸ™ğŸ‘ŒğŸ•ŠğŸ˜ğŸ³â¤â€ğŸ”¥ğŸ’¯âš¡ğŸ†"
RANDOM_LEVEL = "2"
RESTRICTED_CHATS = "1234,5678"