name = "Autoreactt_Bot"
main = "api/worker.js"
compatibility_date = "2024-06-02"

[vars]
BOT_TOKEN = "12345678:PAST-YOUR-BOT-TOKEN-HERE"
BOT_USERNAME = "Autoreactt_Bot"
EMOJI_LIST = "ğŸ‘â¤ğŸ”¥ğŸ¥°ğŸ‘ğŸ˜ğŸ‰ğŸ¤©ğŸ™ğŸ‘ŒğŸ•ŠğŸ˜ğŸ³â¤â€ğŸ”¥ğŸ’¯âš¡ğŸ†"
RANDOM_LEVEL = "2"
RESTRICTED_CHATS = "1234,5678"